package com.galvyx.app

import org.json.JSONArray
import org.json.JSONObject
import java.util.UUID

enum class StorageMode(val label: String) {
    Device("This Device"),
    SharePoint("Microsoft 365 / SharePoint");

    companion object {
        fun fromRaw(raw: String?): StorageMode = values().firstOrNull { it.name == raw } ?: Device
        fun fromLabel(label: String): StorageMode = values().firstOrNull { it.label == label } ?: Device
    }
}

data class CompanyProfile(
    val companyName: String = "",
    val technicianName: String = "",
    val reportFooter: String = "Generated by Galvyx",
    val storageMode: StorageMode = StorageMode.Device,
    val localRootFolder: String = "Galvyx",
    val localReportsFolder: String = "Reports",
    val localPhotosFolder: String = "Photos",
    val localReportsTreeUri: String = "",
    val localPhotosTreeUri: String = "",
    val backupTreeUri: String = "",
    val autoBackupEnabled: Boolean = false,
    val sharePointSiteUrl: String = "",
    val sharePointLibraryName: String = "Documents",
    val sharePointFolderPath: String = "Galvyx/Site Visits"
) {
    fun toJson(): JSONObject = JSONObject()
        .put("companyName", companyName)
        .put("technicianName", technicianName)
        .put("reportFooter", reportFooter)
        .put("storageMode", storageMode.name)
        .put("localRootFolder", localRootFolder)
        .put("localReportsFolder", localReportsFolder)
        .put("localPhotosFolder", localPhotosFolder)
        .put("localReportsTreeUri", localReportsTreeUri)
        .put("localPhotosTreeUri", localPhotosTreeUri)
        .put("backupTreeUri", backupTreeUri)
        .put("autoBackupEnabled", autoBackupEnabled)
        .put("sharePointSiteUrl", sharePointSiteUrl)
        .put("sharePointLibraryName", sharePointLibraryName)
        .put("sharePointFolderPath", sharePointFolderPath)

    companion object {
        fun fromJson(json: JSONObject): CompanyProfile = CompanyProfile(
            companyName = json.optString("companyName"),
            technicianName = json.optString("technicianName"),
            reportFooter = json.optString("reportFooter", "Generated by Galvyx"),
            storageMode = StorageMode.fromRaw(json.optString("storageMode", StorageMode.Device.name)),
            localRootFolder = json.optString("localRootFolder", "Galvyx"),
            localReportsFolder = json.optString("localReportsFolder", "Reports"),
            localPhotosFolder = json.optString("localPhotosFolder", "Photos"),
            localReportsTreeUri = json.optString("localReportsTreeUri"),
            localPhotosTreeUri = json.optString("localPhotosTreeUri"),
            backupTreeUri = json.optString("backupTreeUri"),
            autoBackupEnabled = json.optBoolean("autoBackupEnabled", false),
            sharePointSiteUrl = json.optString("sharePointSiteUrl"),
            sharePointLibraryName = json.optString("sharePointLibraryName", "Documents"),
            sharePointFolderPath = json.optString("sharePointFolderPath", "Galvyx/Site Visits")
        )
    }
}

data class VisitNote(
    val id: String = UUID.randomUUID().toString(),
    val location: String = "",
    val category: String = "General Note",
    val title: String = "",
    val notes: String = ""
) {
    fun toJson(): JSONObject = JSONObject()
        .put("id", id)
        .put("location", location)
        .put("category", category)
        .put("title", title)
        .put("notes", notes)

    companion object {
        fun fromJson(json: JSONObject): VisitNote = VisitNote(
            id = json.optString("id", UUID.randomUUID().toString()),
            location = json.optString("location"),
            category = json.optString("category", "General Note"),
            title = json.optString("title"),
            notes = json.optString("notes")
        )
    }
}

data class DeviceInfo(
    val id: String = UUID.randomUUID().toString(),
    val location: String = "",
    val deviceType: String = "Other",
    val manufacturer: String = "",
    val model: String = "",
    val serialNumber: String = "",
    val macAddress: String = "",
    val ipAddress: String = "",
    val hostname: String = "",
    val notes: String = ""
) {
    fun toJson(): JSONObject = JSONObject()
        .put("id", id)
        .put("location", location)
        .put("deviceType", deviceType)
        .put("manufacturer", manufacturer)
        .put("model", model)
        .put("serialNumber", serialNumber)
        .put("macAddress", macAddress)
        .put("ipAddress", ipAddress)
        .put("hostname", hostname)
        .put("notes", notes)

    companion object {
        fun fromJson(json: JSONObject): DeviceInfo = DeviceInfo(
            id = json.optString("id", UUID.randomUUID().toString()),
            location = json.optString("location"),
            deviceType = json.optString("deviceType", "Other"),
            manufacturer = json.optString("manufacturer"),
            model = json.optString("model"),
            serialNumber = json.optString("serialNumber"),
            macAddress = json.optString("macAddress"),
            ipAddress = json.optString("ipAddress"),
            hostname = json.optString("hostname"),
            notes = json.optString("notes")
        )
    }
}

data class VisitExpense(
    val id: String = UUID.randomUUID().toString(),
    val date: String = "",
    val category: String = "Other",
    val vendor: String = "",
    val amount: String = "",
    val paymentMethod: String = "Reimbursable",
    val notes: String = "",
    val receiptPhotoPaths: List<String> = emptyList()
) {
    val receiptCountLabel: String
        get() = when (receiptPhotoPaths.size) {
            0 -> "No receipts"
            1 -> "1 receipt scan"
            else -> "${receiptPhotoPaths.size} receipt scans"
        }

    fun toJson(): JSONObject = JSONObject()
        .put("id", id)
        .put("date", date)
        .put("category", category)
        .put("vendor", vendor)
        .put("amount", amount)
        .put("paymentMethod", paymentMethod)
        .put("notes", notes)
        .put("receiptPhotoPaths", JSONArray().also { array -> receiptPhotoPaths.forEach { array.put(it) } })

    companion object {
        fun fromJson(json: JSONObject): VisitExpense = VisitExpense(
            id = json.optString("id", UUID.randomUUID().toString()),
            date = json.optString("date"),
            category = json.optString("category", "Other"),
            vendor = json.optString("vendor"),
            amount = json.optString("amount"),
            paymentMethod = json.optString("paymentMethod", "Reimbursable"),
            notes = json.optString("notes"),
            receiptPhotoPaths = json.optJSONArray("receiptPhotoPaths").toStringList()
        )
    }
}

data class ExpenseGroupTotal(
    val label: String,
    val count: Int,
    val total: Double
)

data class ExpenseBreakdown(
    val total: Double,
    val reimbursableTotal: Double,
    val companyPaidTotal: Double,
    val receiptAttachedTotal: Double,
    val missingReceiptTotal: Double,
    val receiptScanCount: Int,
    val missingReceiptCount: Int,
    val byCategory: List<ExpenseGroupTotal>,
    val byPaymentMethod: List<ExpenseGroupTotal>
)

data class VisitPhoto(
    val id: String = UUID.randomUUID().toString(),
    val path: String,
    val caption: String = "",
    val category: String = "General",
    val stage: String = "Reference",
    val rotationDegrees: Int = 0,
    val isKeyPhoto: Boolean = false
) {
    fun toJson(): JSONObject = JSONObject()
        .put("id", id)
        .put("path", path)
        .put("caption", caption)
        .put("category", category)
        .put("stage", stage)
        .put("rotationDegrees", rotationDegrees)
        .put("isKeyPhoto", isKeyPhoto)

    val reportLabel: String
        get() = listOf(category, stage).filter { it.isNotBlank() }.joinToString(" • ").ifBlank { "Photo" }

    companion object {
        fun fromJson(json: JSONObject): VisitPhoto = VisitPhoto(
            id = json.optString("id", UUID.randomUUID().toString()),
            path = json.optString("path"),
            caption = json.optString("caption"),
            category = json.optString("category", "General"),
            stage = json.optString("stage", "Reference"),
            rotationDegrees = json.optInt("rotationDegrees", 0).normalizedRotationDegrees(),
            isKeyPhoto = json.optBoolean("isKeyPhoto", false)
        )
    }
}

fun Int.normalizedRotationDegrees(): Int = ((this % 360) + 360) % 360

data class CoreSystems(
    val emailPlatform: String = "Unknown",
    val emailDomain: String = "",
    val adminPortal: String = "",
    val mfaStatus: String = "Unknown",
    val fileStorage: String = "Unknown",
    val backupPlatform: String = "Unknown",
    val securityPlatform: String = "Unknown",
    val firewallPlatform: String = "Unknown",
    val wifiPlatform: String = "Unknown",
    val rmmPlatform: String = "Unknown",
    val lineOfBusinessApps: String = "",
    val notes: String = ""
) {
    val summaryRows: List<Pair<String, String>>
        get() = listOf(
            "Email" to listOf(emailPlatform, emailDomain).filter { it.isNotBlank() && it != "Unknown" }.joinToString(" • ").ifBlank { emailPlatform },
            "Admin Portal" to adminPortal,
            "MFA" to mfaStatus,
            "File Storage" to fileStorage,
            "Backups" to backupPlatform,
            "Security" to securityPlatform,
            "Firewall" to firewallPlatform,
            "Wi-Fi" to wifiPlatform,
            "RMM" to rmmPlatform,
            "Business Apps" to lineOfBusinessApps,
            "Notes" to notes
        ).filter { it.second.isNotBlank() && it.second != "Unknown" }

    fun toJson(): JSONObject = JSONObject()
        .put("emailPlatform", emailPlatform)
        .put("emailDomain", emailDomain)
        .put("adminPortal", adminPortal)
        .put("mfaStatus", mfaStatus)
        .put("fileStorage", fileStorage)
        .put("backupPlatform", backupPlatform)
        .put("securityPlatform", securityPlatform)
        .put("firewallPlatform", firewallPlatform)
        .put("wifiPlatform", wifiPlatform)
        .put("rmmPlatform", rmmPlatform)
        .put("lineOfBusinessApps", lineOfBusinessApps)
        .put("notes", notes)

    companion object {
        fun fromJson(json: JSONObject?): CoreSystems = CoreSystems(
            emailPlatform = json?.optString("emailPlatform", "Unknown") ?: "Unknown",
            emailDomain = json?.optString("emailDomain") ?: "",
            adminPortal = json?.optString("adminPortal") ?: "",
            mfaStatus = json?.optString("mfaStatus", "Unknown") ?: "Unknown",
            fileStorage = json?.optString("fileStorage", "Unknown") ?: "Unknown",
            backupPlatform = json?.optString("backupPlatform", "Unknown") ?: "Unknown",
            securityPlatform = json?.optString("securityPlatform", "Unknown") ?: "Unknown",
            firewallPlatform = json?.optString("firewallPlatform", "Unknown") ?: "Unknown",
            wifiPlatform = json?.optString("wifiPlatform", "Unknown") ?: "Unknown",
            rmmPlatform = json?.optString("rmmPlatform", "Unknown") ?: "Unknown",
            lineOfBusinessApps = json?.optString("lineOfBusinessApps") ?: "",
            notes = json?.optString("notes") ?: ""
        )
    }
}

data class SiteVisit(
    val id: String = UUID.randomUUID().toString(),
    val clientName: String = "",
    val projectName: String = "",
    val technicianName: String = "",
    val date: String = "",
    val jobType: String = "General Service Call",
    val clientType: String = "General Business",
    val coreSystems: CoreSystems = CoreSystems(),
    val notes: List<VisitNote> = emptyList(),
    val devices: List<DeviceInfo> = emptyList(),
    val expenses: List<VisitExpense> = emptyList(),
    val photos: List<VisitPhoto> = emptyList()
) {
    val title: String
        get() = listOf(clientName, projectName).filter { it.isNotBlank() }.joinToString(" • ").ifBlank { "Untitled Visit" }

    fun summary(): String = "${notes.size} notes • ${devices.size} devices • ${expenses.size} expenses • ${photos.size} photos"

    val clientTypeLabel: String
        get() = clientType.ifBlank { "General Business" }

    val expenseBreakdown: ExpenseBreakdown
        get() {
            val totals = expenses.map { it to it.amount.moneyValueOrZero() }
            fun grouped(selector: (VisitExpense) -> String): List<ExpenseGroupTotal> = totals
                .groupBy { (expense, _) -> selector(expense).ifBlank { "Other" } }
                .map { (label, rows) -> ExpenseGroupTotal(label = label, count = rows.size, total = rows.sumOf { it.second }) }
                .sortedWith(compareByDescending<ExpenseGroupTotal> { it.total }.thenBy { it.label })

            return ExpenseBreakdown(
                total = totals.sumOf { it.second },
                reimbursableTotal = totals.filter { it.first.paymentMethod.equals("Reimbursable", ignoreCase = true) }.sumOf { it.second },
                companyPaidTotal = totals.filterNot { it.first.paymentMethod.equals("Reimbursable", ignoreCase = true) }.sumOf { it.second },
                receiptAttachedTotal = totals.filter { it.first.receiptPhotoPaths.isNotEmpty() }.sumOf { it.second },
                missingReceiptTotal = totals.filter { it.first.receiptPhotoPaths.isEmpty() }.sumOf { it.second },
                receiptScanCount = expenses.sumOf { it.receiptPhotoPaths.size },
                missingReceiptCount = expenses.count { it.receiptPhotoPaths.isEmpty() },
                byCategory = grouped { it.category },
                byPaymentMethod = grouped { it.paymentMethod }
            )
        }

    fun matchesSearch(query: String): Boolean {
        val normalized = query.trim().lowercase()
        if (normalized.isBlank()) return true
        return listOf(
            clientName,
            projectName,
            technicianName,
            date,
            jobType,
            clientTypeLabel,
            coreSystems.summaryRows.joinToString(" ") { "${it.first} ${it.second}" },
            notes.joinToString(" ") { listOf(it.location, it.category, it.title, it.notes).joinToString(" ") },
            devices.joinToString(" ") { listOf(it.location, it.deviceType, it.manufacturer, it.model, it.serialNumber, it.macAddress, it.ipAddress, it.hostname, it.notes).joinToString(" ") },
            expenses.joinToString(" ") { listOf(it.date, it.category, it.vendor, it.amount, it.paymentMethod, it.notes, it.receiptCountLabel).joinToString(" ") },
            photos.joinToString(" ") { listOf(it.category, it.stage, it.caption, if (it.isKeyPhoto) "key photo" else "").joinToString(" ") }
        ).joinToString(" ").lowercase().contains(normalized)
    }

    fun toJson(): JSONObject = JSONObject()
        .put("id", id)
        .put("clientName", clientName)
        .put("projectName", projectName)
        .put("technicianName", technicianName)
        .put("date", date)
        .put("jobType", jobType)
        .put("clientType", clientTypeLabel)
        .put("coreSystems", coreSystems.toJson())
        .put("notes", notes.toJsonArray { it.toJson() })
        .put("devices", devices.toJsonArray { it.toJson() })
        .put("expenses", expenses.toJsonArray { it.toJson() })
        .put("photos", photos.toJsonArray { it.toJson() })

    companion object {
        fun fromJson(json: JSONObject): SiteVisit = SiteVisit(
            id = json.optString("id", UUID.randomUUID().toString()),
            clientName = json.optString("clientName"),
            projectName = json.optString("projectName"),
            technicianName = json.optString("technicianName"),
            date = json.optString("date"),
            jobType = json.optString("jobType", "General Service Call"),
            clientType = json.optString("clientType", "General Business"),
            coreSystems = CoreSystems.fromJson(json.optJSONObject("coreSystems")),
            notes = json.optJSONArray("notes").toList { VisitNote.fromJson(it) },
            devices = json.optJSONArray("devices").toList { DeviceInfo.fromJson(it) },
            expenses = json.optJSONArray("expenses").toList { VisitExpense.fromJson(it) },
            photos = json.optJSONArray("photos").toList { VisitPhoto.fromJson(it) }
        )
    }
}

fun visitsToJson(visits: List<SiteVisit>): String = visits.toJsonArray { it.toJson() }.toString()

fun visitsFromJson(raw: String?): List<SiteVisit> {
    if (raw.isNullOrBlank()) return emptyList()
    return runCatching {
        JSONArray(raw).toList { SiteVisit.fromJson(it) }
    }.getOrDefault(emptyList())
}

data class GalvyxBackup(
    val profile: CompanyProfile,
    val visits: List<SiteVisit>
) {
    fun toJson(): JSONObject = JSONObject()
        .put("schema", "com.galvyx.backup")
        .put("version", 1)
        .put("profile", profile.toJson())
        .put("visits", visits.toJsonArray { it.toJson() })

    companion object {
        fun fromJson(raw: String): GalvyxBackup {
            val json = JSONObject(raw)
            return GalvyxBackup(
                profile = json.optJSONObject("profile")?.let { CompanyProfile.fromJson(it) } ?: CompanyProfile(),
                visits = json.optJSONArray("visits").toList { SiteVisit.fromJson(it) }
            )
        }
    }
}

fun backupToJson(profile: CompanyProfile, visits: List<SiteVisit>): String = GalvyxBackup(profile, visits).toJson().toString()

fun backupFromJson(raw: String): GalvyxBackup? = runCatching { GalvyxBackup.fromJson(raw) }.getOrNull()

private fun <T> List<T>.toJsonArray(transform: (T) -> JSONObject): JSONArray {
    val array = JSONArray()
    forEach { array.put(transform(it)) }
    return array
}

private fun <T> JSONArray?.toList(transform: (JSONObject) -> T): List<T> {
    if (this == null) return emptyList()
    return buildList {
        for (index in 0 until length()) {
            optJSONObject(index)?.let { add(transform(it)) }
        }
    }
}

private fun String.moneyValueOrZero(): Double = replace("$", "").replace(",", "").trim().toDoubleOrNull() ?: 0.0

private fun JSONArray?.toStringList(): List<String> {
    if (this == null) return emptyList()
    return buildList {
        for (index in 0 until length()) {
            optString(index).takeIf { it.isNotBlank() }?.let { add(it) }
        }
    }
}
