package com.galvyx.app

import org.json.JSONArray
import org.json.JSONObject
import java.util.UUID

data class CompanyProfile(
    val companyName: String = "",
    val technicianName: String = "",
    val reportFooter: String = "Generated by Galvyx"
) {
    fun toJson(): JSONObject = JSONObject()
        .put("companyName", companyName)
        .put("technicianName", technicianName)
        .put("reportFooter", reportFooter)

    companion object {
        fun fromJson(json: JSONObject): CompanyProfile = CompanyProfile(
            companyName = json.optString("companyName"),
            technicianName = json.optString("technicianName"),
            reportFooter = json.optString("reportFooter", "Generated by Galvyx")
        )
    }
}

data class VisitNote(
    val id: String = UUID.randomUUID().toString(),
    val location: String = "",
    val category: String = "General Note",
    val title: String = "",
    val notes: String = ""
) {
    fun toJson(): JSONObject = JSONObject()
        .put("id", id)
        .put("location", location)
        .put("category", category)
        .put("title", title)
        .put("notes", notes)

    companion object {
        fun fromJson(json: JSONObject): VisitNote = VisitNote(
            id = json.optString("id", UUID.randomUUID().toString()),
            location = json.optString("location"),
            category = json.optString("category", "General Note"),
            title = json.optString("title"),
            notes = json.optString("notes")
        )
    }
}

data class DeviceInfo(
    val id: String = UUID.randomUUID().toString(),
    val location: String = "",
    val deviceType: String = "Other",
    val manufacturer: String = "",
    val model: String = "",
    val serialNumber: String = "",
    val macAddress: String = "",
    val ipAddress: String = "",
    val hostname: String = "",
    val notes: String = ""
) {
    fun toJson(): JSONObject = JSONObject()
        .put("id", id)
        .put("location", location)
        .put("deviceType", deviceType)
        .put("manufacturer", manufacturer)
        .put("model", model)
        .put("serialNumber", serialNumber)
        .put("macAddress", macAddress)
        .put("ipAddress", ipAddress)
        .put("hostname", hostname)
        .put("notes", notes)

    companion object {
        fun fromJson(json: JSONObject): DeviceInfo = DeviceInfo(
            id = json.optString("id", UUID.randomUUID().toString()),
            location = json.optString("location"),
            deviceType = json.optString("deviceType", "Other"),
            manufacturer = json.optString("manufacturer"),
            model = json.optString("model"),
            serialNumber = json.optString("serialNumber"),
            macAddress = json.optString("macAddress"),
            ipAddress = json.optString("ipAddress"),
            hostname = json.optString("hostname"),
            notes = json.optString("notes")
        )
    }
}

data class VisitExpense(
    val id: String = UUID.randomUUID().toString(),
    val date: String = "",
    val category: String = "Other",
    val vendor: String = "",
    val amount: String = "",
    val paymentMethod: String = "Reimbursable",
    val notes: String = ""
) {
    fun toJson(): JSONObject = JSONObject()
        .put("id", id)
        .put("date", date)
        .put("category", category)
        .put("vendor", vendor)
        .put("amount", amount)
        .put("paymentMethod", paymentMethod)
        .put("notes", notes)

    companion object {
        fun fromJson(json: JSONObject): VisitExpense = VisitExpense(
            id = json.optString("id", UUID.randomUUID().toString()),
            date = json.optString("date"),
            category = json.optString("category", "Other"),
            vendor = json.optString("vendor"),
            amount = json.optString("amount"),
            paymentMethod = json.optString("paymentMethod", "Reimbursable"),
            notes = json.optString("notes")
        )
    }
}

data class VisitPhoto(
    val id: String = UUID.randomUUID().toString(),
    val path: String,
    val caption: String = ""
) {
    fun toJson(): JSONObject = JSONObject()
        .put("id", id)
        .put("path", path)
        .put("caption", caption)

    companion object {
        fun fromJson(json: JSONObject): VisitPhoto = VisitPhoto(
            id = json.optString("id", UUID.randomUUID().toString()),
            path = json.optString("path"),
            caption = json.optString("caption")
        )
    }
}

data class SiteVisit(
    val id: String = UUID.randomUUID().toString(),
    val clientName: String = "",
    val projectName: String = "",
    val technicianName: String = "",
    val date: String = "",
    val jobType: String = "General Service Call",
    val notes: List<VisitNote> = emptyList(),
    val devices: List<DeviceInfo> = emptyList(),
    val expenses: List<VisitExpense> = emptyList(),
    val photos: List<VisitPhoto> = emptyList()
) {
    val title: String
        get() = listOf(clientName, projectName).filter { it.isNotBlank() }.joinToString(" • ").ifBlank { "Untitled Visit" }

    fun summary(): String = "${notes.size} notes • ${devices.size} devices • ${expenses.size} expenses • ${photos.size} photos"

    fun toJson(): JSONObject = JSONObject()
        .put("id", id)
        .put("clientName", clientName)
        .put("projectName", projectName)
        .put("technicianName", technicianName)
        .put("date", date)
        .put("jobType", jobType)
        .put("notes", notes.toJsonArray { it.toJson() })
        .put("devices", devices.toJsonArray { it.toJson() })
        .put("expenses", expenses.toJsonArray { it.toJson() })
        .put("photos", photos.toJsonArray { it.toJson() })

    companion object {
        fun fromJson(json: JSONObject): SiteVisit = SiteVisit(
            id = json.optString("id", UUID.randomUUID().toString()),
            clientName = json.optString("clientName"),
            projectName = json.optString("projectName"),
            technicianName = json.optString("technicianName"),
            date = json.optString("date"),
            jobType = json.optString("jobType", "General Service Call"),
            notes = json.optJSONArray("notes").toList { VisitNote.fromJson(it) },
            devices = json.optJSONArray("devices").toList { DeviceInfo.fromJson(it) },
            expenses = json.optJSONArray("expenses").toList { VisitExpense.fromJson(it) },
            photos = json.optJSONArray("photos").toList { VisitPhoto.fromJson(it) }
        )
    }
}

fun visitsToJson(visits: List<SiteVisit>): String = visits.toJsonArray { it.toJson() }.toString()

fun visitsFromJson(raw: String?): List<SiteVisit> {
    if (raw.isNullOrBlank()) return emptyList()
    return runCatching {
        JSONArray(raw).toList { SiteVisit.fromJson(it) }
    }.getOrDefault(emptyList())
}

private fun <T> List<T>.toJsonArray(transform: (T) -> JSONObject): JSONArray {
    val array = JSONArray()
    forEach { array.put(transform(it)) }
    return array
}

private fun <T> JSONArray?.toList(transform: (JSONObject) -> T): List<T> {
    if (this == null) return emptyList()
    return buildList {
        for (index in 0 until length()) {
            optJSONObject(index)?.let { add(transform(it)) }
        }
    }
}
