package com.galvyx.app

import org.json.JSONArray
import org.json.JSONObject
import java.util.UUID

enum class StorageMode(val label: String) {
    Device("This Device"),
    SharePoint("Microsoft 365 / SharePoint");

    companion object {
        fun fromRaw(raw: String?): StorageMode = values().firstOrNull { it.name == raw } ?: Device
        fun fromLabel(label: String): StorageMode = values().firstOrNull { it.label == label } ?: Device
    }
}

data class CompanyProfile(
    val companyName: String = "",
    val technicianName: String = "",
    val reportFooter: String = "Generated by Galvyx",
    val storageMode: StorageMode = StorageMode.Device,
    val localRootFolder: String = "Galvyx",
    val localReportsFolder: String = "Reports",
    val localPhotosFolder: String = "Photos",
    val localReportsTreeUri: String = "",
    val localPhotosTreeUri: String = "",
    val sharePointSiteUrl: String = "",
    val sharePointLibraryName: String = "Documents",
    val sharePointFolderPath: String = "Galvyx/Site Visits"
) {
    fun toJson(): JSONObject = JSONObject()
        .put("companyName", companyName)
        .put("technicianName", technicianName)
        .put("reportFooter", reportFooter)
        .put("storageMode", storageMode.name)
        .put("localRootFolder", localRootFolder)
        .put("localReportsFolder", localReportsFolder)
        .put("localPhotosFolder", localPhotosFolder)
        .put("localReportsTreeUri", localReportsTreeUri)
        .put("localPhotosTreeUri", localPhotosTreeUri)
        .put("sharePointSiteUrl", sharePointSiteUrl)
        .put("sharePointLibraryName", sharePointLibraryName)
        .put("sharePointFolderPath", sharePointFolderPath)

    companion object {
        fun fromJson(json: JSONObject): CompanyProfile = CompanyProfile(
            companyName = json.optString("companyName"),
            technicianName = json.optString("technicianName"),
            reportFooter = json.optString("reportFooter", "Generated by Galvyx"),
            storageMode = StorageMode.fromRaw(json.optString("storageMode", StorageMode.Device.name)),
            localRootFolder = json.optString("localRootFolder", "Galvyx"),
            localReportsFolder = json.optString("localReportsFolder", "Reports"),
            localPhotosFolder = json.optString("localPhotosFolder", "Photos"),
            localReportsTreeUri = json.optString("localReportsTreeUri"),
            localPhotosTreeUri = json.optString("localPhotosTreeUri"),
            sharePointSiteUrl = json.optString("sharePointSiteUrl"),
            sharePointLibraryName = json.optString("sharePointLibraryName", "Documents"),
            sharePointFolderPath = json.optString("sharePointFolderPath", "Galvyx/Site Visits")
        )
    }
}

data class VisitNote(
    val id: String = UUID.randomUUID().toString(),
    val location: String = "",
    val category: String = "General Note",
    val title: String = "",
    val notes: String = ""
) {
    fun toJson(): JSONObject = JSONObject()
        .put("id", id)
        .put("location", location)
        .put("category", category)
        .put("title", title)
        .put("notes", notes)

    companion object {
        fun fromJson(json: JSONObject): VisitNote = VisitNote(
            id = json.optString("id", UUID.randomUUID().toString()),
            location = json.optString("location"),
            category = json.optString("category", "General Note"),
            title = json.optString("title"),
            notes = json.optString("notes")
        )
    }
}

data class DeviceInfo(
    val id: String = UUID.randomUUID().toString(),
    val location: String = "",
    val deviceType: String = "Other",
    val manufacturer: String = "",
    val model: String = "",
    val serialNumber: String = "",
    val macAddress: String = "",
    val ipAddress: String = "",
    val hostname: String = "",
    val notes: String = ""
) {
    fun toJson(): JSONObject = JSONObject()
        .put("id", id)
        .put("location", location)
        .put("deviceType", deviceType)
        .put("manufacturer", manufacturer)
        .put("model", model)
        .put("serialNumber", serialNumber)
        .put("macAddress", macAddress)
        .put("ipAddress", ipAddress)
        .put("hostname", hostname)
        .put("notes", notes)

    companion object {
        fun fromJson(json: JSONObject): DeviceInfo = DeviceInfo(
            id = json.optString("id", UUID.randomUUID().toString()),
            location = json.optString("location"),
            deviceType = json.optString("deviceType", "Other"),
            manufacturer = json.optString("manufacturer"),
            model = json.optString("model"),
            serialNumber = json.optString("serialNumber"),
            macAddress = json.optString("macAddress"),
            ipAddress = json.optString("ipAddress"),
            hostname = json.optString("hostname"),
            notes = json.optString("notes")
        )
    }
}

data class VisitExpense(
    val id: String = UUID.randomUUID().toString(),
    val date: String = "",
    val category: String = "Other",
    val vendor: String = "",
    val amount: String = "",
    val paymentMethod: String = "Reimbursable",
    val notes: String = ""
) {
    fun toJson(): JSONObject = JSONObject()
        .put("id", id)
        .put("date", date)
        .put("category", category)
        .put("vendor", vendor)
        .put("amount", amount)
        .put("paymentMethod", paymentMethod)
        .put("notes", notes)

    companion object {
        fun fromJson(json: JSONObject): VisitExpense = VisitExpense(
            id = json.optString("id", UUID.randomUUID().toString()),
            date = json.optString("date"),
            category = json.optString("category", "Other"),
            vendor = json.optString("vendor"),
            amount = json.optString("amount"),
            paymentMethod = json.optString("paymentMethod", "Reimbursable"),
            notes = json.optString("notes")
        )
    }
}

data class VisitPhoto(
    val id: String = UUID.randomUUID().toString(),
    val path: String,
    val caption: String = "",
    val category: String = "General",
    val stage: String = "Reference"
) {
    fun toJson(): JSONObject = JSONObject()
        .put("id", id)
        .put("path", path)
        .put("caption", caption)
        .put("category", category)
        .put("stage", stage)

    val reportLabel: String
        get() = listOf(category, stage).filter { it.isNotBlank() }.joinToString(" • ").ifBlank { "Photo" }

    companion object {
        fun fromJson(json: JSONObject): VisitPhoto = VisitPhoto(
            id = json.optString("id", UUID.randomUUID().toString()),
            path = json.optString("path"),
            caption = json.optString("caption"),
            category = json.optString("category", "General"),
            stage = json.optString("stage", "Reference")
        )
    }
}

data class SiteVisit(
    val id: String = UUID.randomUUID().toString(),
    val clientName: String = "",
    val projectName: String = "",
    val technicianName: String = "",
    val date: String = "",
    val jobType: String = "General Service Call",
    val notes: List<VisitNote> = emptyList(),
    val devices: List<DeviceInfo> = emptyList(),
    val expenses: List<VisitExpense> = emptyList(),
    val photos: List<VisitPhoto> = emptyList()
) {
    val title: String
        get() = listOf(clientName, projectName).filter { it.isNotBlank() }.joinToString(" • ").ifBlank { "Untitled Visit" }

    fun summary(): String = "${notes.size} notes • ${devices.size} devices • ${expenses.size} expenses • ${photos.size} photos"

    fun matchesSearch(query: String): Boolean {
        val normalized = query.trim().lowercase()
        if (normalized.isBlank()) return true
        return listOf(
            clientName,
            projectName,
            technicianName,
            date,
            jobType,
            notes.joinToString(" ") { listOf(it.location, it.category, it.title, it.notes).joinToString(" ") },
            devices.joinToString(" ") { listOf(it.location, it.deviceType, it.manufacturer, it.model, it.serialNumber, it.macAddress, it.ipAddress, it.hostname, it.notes).joinToString(" ") },
            expenses.joinToString(" ") { listOf(it.date, it.category, it.vendor, it.amount, it.paymentMethod, it.notes).joinToString(" ") },
            photos.joinToString(" ") { listOf(it.category, it.stage, it.caption).joinToString(" ") }
        ).joinToString(" ").lowercase().contains(normalized)
    }

    fun toJson(): JSONObject = JSONObject()
        .put("id", id)
        .put("clientName", clientName)
        .put("projectName", projectName)
        .put("technicianName", technicianName)
        .put("date", date)
        .put("jobType", jobType)
        .put("notes", notes.toJsonArray { it.toJson() })
        .put("devices", devices.toJsonArray { it.toJson() })
        .put("expenses", expenses.toJsonArray { it.toJson() })
        .put("photos", photos.toJsonArray { it.toJson() })

    companion object {
        fun fromJson(json: JSONObject): SiteVisit = SiteVisit(
            id = json.optString("id", UUID.randomUUID().toString()),
            clientName = json.optString("clientName"),
            projectName = json.optString("projectName"),
            technicianName = json.optString("technicianName"),
            date = json.optString("date"),
            jobType = json.optString("jobType", "General Service Call"),
            notes = json.optJSONArray("notes").toList { VisitNote.fromJson(it) },
            devices = json.optJSONArray("devices").toList { DeviceInfo.fromJson(it) },
            expenses = json.optJSONArray("expenses").toList { VisitExpense.fromJson(it) },
            photos = json.optJSONArray("photos").toList { VisitPhoto.fromJson(it) }
        )
    }
}

fun visitsToJson(visits: List<SiteVisit>): String = visits.toJsonArray { it.toJson() }.toString()

fun visitsFromJson(raw: String?): List<SiteVisit> {
    if (raw.isNullOrBlank()) return emptyList()
    return runCatching {
        JSONArray(raw).toList { SiteVisit.fromJson(it) }
    }.getOrDefault(emptyList())
}

data class GalvyxBackup(
    val profile: CompanyProfile,
    val visits: List<SiteVisit>
) {
    fun toJson(): JSONObject = JSONObject()
        .put("schema", "com.galvyx.backup")
        .put("version", 1)
        .put("profile", profile.toJson())
        .put("visits", visits.toJsonArray { it.toJson() })

    companion object {
        fun fromJson(raw: String): GalvyxBackup {
            val json = JSONObject(raw)
            return GalvyxBackup(
                profile = json.optJSONObject("profile")?.let { CompanyProfile.fromJson(it) } ?: CompanyProfile(),
                visits = json.optJSONArray("visits").toList { SiteVisit.fromJson(it) }
            )
        }
    }
}

fun backupToJson(profile: CompanyProfile, visits: List<SiteVisit>): String = GalvyxBackup(profile, visits).toJson().toString()

fun backupFromJson(raw: String): GalvyxBackup? = runCatching { GalvyxBackup.fromJson(raw) }.getOrNull()

private fun <T> List<T>.toJsonArray(transform: (T) -> JSONObject): JSONArray {
    val array = JSONArray()
    forEach { array.put(transform(it)) }
    return array
}

private fun <T> JSONArray?.toList(transform: (JSONObject) -> T): List<T> {
    if (this == null) return emptyList()
    return buildList {
        for (index in 0 until length()) {
            optJSONObject(index)?.let { add(transform(it)) }
        }
    }
}
